<h2> <?= $alimento->nombre_alimento ?> </h2>
<p> Descripción: <?= $alimento->descripcion_alimento ?> </p>
<h4> Información nutricional cada 100gr. </h4>
<p> Calorías: <?= $alimento->calorias ?> kcal. </p>
<p> Proteínas: <?= $alimento->proteinas ?> gr. </p>
<p> Carbohidratos: <?= $alimento->carbohidratos ?> gr. </p>
<p> Grasas: <?= $alimento->grasas ?> gr. </p>
<p> Fibra: <?= $alimento->fibras ?> gr. </p>

<?php require_once 'templates/layout/footer.phtml'; ?>