<br>
<h2>Editar un alimento:</h2>

<h3> Ingrese los nuevos datos: </h3>

<form action="actualizar_alimento" method="POST" class="my-4">
    <!-- ID con campo oculto para pasarlo. -->
    <input type="hidden" name="id_alimento" value="<?=htmlspecialchars($alimento->id_alimento) ?>">  
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="E_nombre_alimento"> Nuevo nombre del alimento </label>
                    <input required name="E_nombre_alimento" type="text" class="form-control" value=" <?=htmlspecialchars($alimento->nombre_alimento)?>" required>
                    
                    <label for="E_descripcion_alimento"> Nueva Descripción </label>
                    <input required name="E_descripcion_alimento" type="text" class="form-control" value=" <?= htmlspecialchars($alimento->descripcion_alimento) ?>" required>

                    <div class="col-md-6">    
                        <div class="form-group">
                            <label for="E_grupo">Grupo</label>
                                <select name="id_grupo" class="form-control" required >
                                    <?php foreach ($grupos as $grupo): ?>
                                        <option value="<?= $grupo->id_grupo?>" <?= ($grupo->id_grupo == $alimento->id_grupo) ? 'selected' : '' ?>>
                                        <?= htmlspecialchars($grupo->nombre_grupo) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                        </div>
                </div>

                    <label for="E_calorias"> Calorías (cada 100gr.) </label>
                    <input required name="E_calorias" type="text" class="form-control" placeholder="<?= $alimento->calorias ?>">

                    <label for="E_proteinas"> Proteínas (cada 100gr.) </label>
                    <input required name="E_proteinas" type="text" class="form-control" placeholder="<?= $alimento->proteinas ?>">

                    <label for="E_carbohidratos"> Carbohidratos (cada 100gr.) </label>
                    <input required name="E_carbohidratos" type="text" class="form-control" placeholder="<?= $alimento->carbohidratos ?>">

                    <label for="E_grasas"> Grasas (cada 100gr.) </label>
                    <input required name="E_grasas" type="text" class="form-control" placeholder="<?= $alimento->grasas ?>">

                    <label for="E_fibras"> Fibras (cada 100gr.) </label>
                    <input required name="E_fibras" type="text" class="form-control" placeholder="<?= $alimento->fibras ?>">

                    <label for="E_imagen_alimento"> Foto del alimento (URL). </label>
                    <input required name="E_imagen_alimento" type="url" class="form-control" <?= htmlspecialchars($alimento->imagen_alimento) ?>">
                </div>
            </div>    
        <div class="col-9">
            <br>
            <button type="submit" class="btn btn-outline-secondary"> Editar </button>                
     </div>                                
</form>



<?php require 'templates/layout/footer.phtml'; ?>