<?php if ($error): ?>
    <div class="alert alert-danger" role="alert">
        <?= $error ?>
    </div>
<?php endif ?>

<form method="POST" action="login">
    <div class="alert alert-info" role="alert">
        <p> Es necesario iniciar sesión para realizar cambios. Complete los campos a continuación.</p>
    </div>

    <div class="form-group">
        <label for="nombre_usuario"> Usuario </label>
        <input type="text" class="form-control" id="nombre_usuario" name="nombre_usuario" required>
    </div>

    <div class="form-group">
        <label for="contraseña"> Contraseña </label>
        <input type="password" class="form-control" id="contraseña" name="contraseña" required>
    </div>
    <br>
    <button type="submit" class="btn btn-outline-success"> Iniciar Sesión </button>
</form>

<?php require_once 'templates/layout/footer.phtml'; ?>
