<?php if ($error): ?>
    <div class="alert alert-danger" role="alert">
        <?= $error ?>
    </div>
<?php endif ?>

<div>
    <h2> Iniciar Sesión: </h2>
</div>
<form method="POST" action="login" class="fs-5 p-3">
    <div class="form-group">
        <label for="nombre_usuario"> Usuario </label>
        <input type="text" class="form-control" id="nombre_usuario" name="nombre_usuario" required>
    </div>
    <br>
    <div class="form-group">
        <label for="contraseña"> Contraseña </label>
        <input type="password" class="form-control" id="contraseña" name="contraseña" required>
    </div>
    <br>
    <button type="submit" class="btn btn-outline-success"> Iniciar Sesión </button>
</form>

<?php require_once 'templates/layout/footer.phtml'; ?>
