
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title> Nutri APP </title>
</head>
<body>
        <header>
            <nav class="navbar navbar-expand-lg bg-light">
                <div class="container-fluid">
                   
                        
                    <a class="navbar-brand" href="home"> NutriAPP 2025</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <?php if (!empty($usuario->id_usuario)): ?> <!-- para los usuarios logeados -->
                                <li class="nav-item">
                                    <span class="nombre_usuario">¡Hola, <?= $usuario->nombre_usuario ?>! </span>
                                </li>
                            <?php endif; ?>
                            <?php if (empty($usuario->id_usuario)): ?>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="listar_grupos"> Grupos alimenticios </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="listar_alimentos"> Alimentos </a>
                                </li>
                            <?php else: ?>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="admin_grupos"> Grupos alimenticios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="admin_alimentos"> Alimentos </a>
                                </li>
                            <?php endif ?>

                            <?php if (empty($usuario->id_usuario)): ?>
                                <li class="nav-item">
                                <b><a class="nav-link active" aria-current="page" href="mostrarLogin">Iniciar sesión</a></b>
                                </li>
                            <?php endif ?>
                            <?php if (!empty($usuario->id_usuario)): ?>
                                 <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="admin_agregar_alimentos"> Administrar Alimentos </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" aria-current="page" href="admin_agregar_grupos"> Administrar Grupos </a>
                                </li>
                           <?php endif ?>
                            <?php if (!empty($usuario->id_usuario)): ?>
                                <li class="nav-item">
                                    <b><a class="nav-link active" aria-current="page" href="logOut"> Cerrar sesión  </a></b>
                                </li>
                            <?php endif ?>
                        </ul>
                    </div>
                </div>
            </nav>
        </header> 

    <main class="container mt-3">
</body>
</html>